"""Shim — canonical source: ``app.dataModel.structure.enums.buildingElement``."""

from app.dataModel.structure.enums.buildingElement import (
    DOOR_BUILDING_ELEMENTS,
    PASSABLE_BUILDING_ELEMENTS,
    STAIR_BUILDING_ELEMENTS,
    STAIR_DIRECTIONAL_ELEMENTS,
    WALKABLE_BUILDING_ELEMENTS,
    WALL_BUILDING_ELEMENTS,
    WALL_OPENING_ELEMENTS,
    StructureElement,
    _DOOR_ELEMENTS,
    _PASSABLE_ELEMENTS,
    _STAIR_DIRECTIONAL,
    _STAIR_ELEMENTS,
    _WALKABLE_ELEMENTS,
    _WALL_ELEMENTS,
    _WALL_OPENING_TYPES,
)

__all__ = [
    "DOOR_BUILDING_ELEMENTS",
    "PASSABLE_BUILDING_ELEMENTS",
    "STAIR_BUILDING_ELEMENTS",
    "STAIR_DIRECTIONAL_ELEMENTS",
    "StructureElement",
    "WALKABLE_BUILDING_ELEMENTS",
    "WALL_BUILDING_ELEMENTS",
    "WALL_OPENING_ELEMENTS",
    "_DOOR_ELEMENTS",
    "_PASSABLE_ELEMENTS",
    "_STAIR_DIRECTIONAL",
    "_STAIR_ELEMENTS",
    "_WALKABLE_ELEMENTS",
    "_WALL_ELEMENTS",
    "_WALL_OPENING_TYPES",
]
