"""REF-W kinds — docs/tz_json_validation.md § REF-W."""

from __future__ import annotations

from enum import StrEnum


class RefKind(StrEnum):
    MATERIAL = "material"
    LIQUID = "liquid"
    TERRAIN = "terrain"
    TERRAIN_CAT = "terrain_cat"
    CLIMATE = "climate"
    WEATHER = "weather"
    CONN = "conn"
    LOC_TYPE = "loc_type"
    LOC_SUBTYPE = "loc_subtype"
    CITY_SIZE = "city_size"
    ECON_TIER = "econ_tier"
    DANGER = "danger"
    CELL_STATE = "cell_state"
    LOC_STATE = "loc_state"
    ROAD = "road"
    PASSAGE = "passage"
    ROOM_TYPE = "room_type"
    BUILDING_TPL = "building_tpl"
    BARRIER_TPL = "barrier_tpl"
    WOUND = "wound"
    COLOUR = "colour"
    TEXTURE = "texture"
    LORE = "lore"
    TAG = "tag"
    INTENSITY = "intensity"
    NARR_TYPE = "narr_type"
    TRAIT = "trait"
    RESPAWN = "respawn"
    NPC_TARGET = "npc_target"
    NPC_NEED = "npc_need"
    NPC_GOAL = "npc_goal"
    RESOURCE = "resource"
    BODY_SCHEMA = "body_schema"
    MAT_USE = "mat_use"
    MUSCLE_TBL = "muscle_tbl"
    CONSTIT_TBL = "constitut_tbl"
    LIGHTING = "lighting"
    MAT_TAG = "mat_tag"
    NPC_LLM_EVT = "npc_llm_evt"
    STAT = "stat"
    SKILL = "skill"
    RESIST = "resist"
