"""
SCH-STRUCTURE — building/barrier/room master data (outside settlement domain).

Structure templates ≠ settlement layout; settlement references structure via templates.
Эталон: docs/tz_building_generator.md, docs/tz_locations.md § structure generation.
"""

from app.dataModel.locations.structure.barrier import (
    BarrierTemplateEntry,
    BarrierTemplateKey,
    WorldBarrierTemplateRegistry,
)
from app.dataModel.locations.structure.building import (
    BuildingBodyTemplate,
    BuildingCatalog,
    BuildingTemplateOutline,
    BuildingTemplateRegistryEntry,
    BuildingTemplateRoomSlot,
    DrawingKey,
    OccupiedFootprintSpec,
    PlotLayoutTemplate,
    StructureCatalog,
    StructureKey,
    StructureTemplate,
    WorldBuildingTemplateRegistry,
    plot_has_building,
    plot_type_defaulted,
    structure_ref_of,
)
from app.dataModel.locations.structure.enums import (
    DEFAULT_BUILDING_PURPOSES,
    DEFAULT_PURPOSE_MATCH,
    HOUSE,
    BuildingPurpose,
    BuildingPurposeMatch,
    coerce_purpose_list,
    coerce_purpose_match,
    primary_purpose,
    purposes_match,
    union_plot_purposes,
    DOOR_BUILDING_ELEMENTS,
    PASSABLE_BUILDING_ELEMENTS,
    STAIR_BUILDING_ELEMENTS,
    STAIR_DIRECTIONAL_ELEMENTS,
    StructureElement,
    WALKABLE_BUILDING_ELEMENTS,
    WALL_BUILDING_ELEMENTS,
    WALL_OPENING_ELEMENTS,
    RoomSize,
    RoomSizePreset,
    SPIRAL_SIZE_PRESETS,
    STRAIGHT_SIZE_PRESETS,
    USHAPE_SIZE_PRESETS,
    SpiralSize,
    StaircaseSizePreset,
    StaircaseType,
    StaircaseTypeSpec,
    StraightSize,
    UShapeSize,
    all_staircase_size_presets,
    default_shaft_footprint_min,
    default_shaft_size_type,
    no_shaft_types,
    requires_shaft,
    staircase_footprint_min,
)
from app.dataModel.locations.structure.materialPick import MaterialPick
from app.dataModel.locations.structure.room import RoomTypeEntry, WorldRoomTypeRegistry

__all__ = [
    "BarrierTemplateEntry",
    "BarrierTemplateKey",
    "BuildingBodyTemplate",
    "BuildingCatalog",
    "BuildingPurpose",
    "BuildingPurposeMatch",
    "BuildingTemplateOutline",
    "BuildingTemplateRegistryEntry",
    "BuildingTemplateRoomSlot",
    "DrawingKey",
    "OccupiedFootprintSpec",
    "PlotLayoutTemplate",
    "StructureCatalog",
    "StructureKey",
    "StructureTemplate",
    "plot_has_building",
    "plot_type_defaulted",
    "structure_ref_of",
    "DEFAULT_BUILDING_PURPOSES",
    "DEFAULT_PURPOSE_MATCH",
    "HOUSE",
    "coerce_purpose_list",
    "coerce_purpose_match",
    "primary_purpose",
    "purposes_match",
    "union_plot_purposes",
    "DOOR_BUILDING_ELEMENTS",
    "MaterialPick",
    "PASSABLE_BUILDING_ELEMENTS",
    "RoomSize",
    "RoomSizePreset",
    "SPIRAL_SIZE_PRESETS",
    "STAIR_BUILDING_ELEMENTS",
    "STAIR_DIRECTIONAL_ELEMENTS",
    "STRAIGHT_SIZE_PRESETS",
    "StructureElement",
    "USHAPE_SIZE_PRESETS",
    "SpiralSize",
    "StaircaseSizePreset",
    "StaircaseType",
    "StaircaseTypeSpec",
    "StraightSize",
    "UShapeSize",
    "all_staircase_size_presets",
    "default_shaft_footprint_min",
    "default_shaft_size_type",
    "no_shaft_types",
    "requires_shaft",
    "staircase_footprint_min",
    "RoomTypeEntry",
    "WorldBarrierTemplateRegistry",
    "WorldBuildingTemplateRegistry",
    "WorldRoomTypeRegistry",
    "WALKABLE_BUILDING_ELEMENTS",
    "WALL_BUILDING_ELEMENTS",
    "WALL_OPENING_ELEMENTS",
]
