from app.application.worldData.generators.coordinates.approachZ import (
    ApproachForm,
    approach_angle_deg,
    clamp_near_z_to_45,
    classify_approach,
)
from app.application.worldData.generators.coordinates.columnSurface import (
    column_surface,
    median_surface_z,
    resolve_district_pin_z,
)
from app.application.worldData.generators.coordinates.convert import (
    cell_size_m,
    coarse_cell_meter_xy,
    coarse_tile_offset_m,
    grid_dimension,
    grid_tile_origin_x,
    grid_tile_origin_y,
    meters_to_grid_x,
    meters_to_grid_y,
    settlement_origin_m,
)
from app.application.worldData.generators.coordinates.rect import (
    cell_in_local_meter_rect,
    cell_in_surface_grid_rect,
    settlement_grid_rect,
    settlement_meter_rect,
)
from app.application.worldData.generators.coordinates.gridRay import walk_grid_ray
from app.application.worldData.generators.coordinates.worldTile import (
    expand_coarse_hydro_to_tile,
    iter_macro_tiles,
    iter_meter_chunks,
    is_macro_grid_coord,
    local_index_x,
    local_index_y,
    macro_bbox_to_meter_bbox,
    macro_tile_of,
    meter_bbox_for_tile,
    tile_index_x,
    tile_index_y,
    tile_origin_x,
    tile_origin_y,
    world_meter_xy,
)
from app.application.worldData.generators.coordinates.space import CoordinateSpace
from app.application.worldData.generators.coordinates.types import (
    GridX,
    GridY,
    LocalMeterCoord,
    LocalMeterRect,
    MeterDelta,
    MeterX,
    MeterY,
    MeterZ,
    SurfaceGridCoord,
    SurfaceGridRect,
)

__all__ = [
    "ApproachForm",
    "approach_angle_deg",
    "clamp_near_z_to_45",
    "classify_approach",
    "column_surface",
    "median_surface_z",
    "resolve_district_pin_z",
    "walk_grid_ray",
    "CoordinateSpace",
    "expand_coarse_hydro_to_tile",
    "iter_macro_tiles",
    "iter_meter_chunks",
    "is_macro_grid_coord",
    "local_index_x",
    "local_index_y",
    "macro_bbox_to_meter_bbox",
    "macro_tile_of",
    "meter_bbox_for_tile",
    "tile_index_x",
    "tile_index_y",
    "tile_origin_x",
    "tile_origin_y",
    "world_meter_xy",
    "GridX",
    "GridY",
    "LocalMeterCoord",
    "LocalMeterRect",
    "MeterDelta",
    "MeterX",
    "MeterY",
    "MeterZ",
    "SurfaceGridCoord",
    "SurfaceGridRect",
    "cell_in_local_meter_rect",
    "cell_in_surface_grid_rect",
    "cell_size_m",
    "coarse_cell_meter_xy",
    "coarse_tile_offset_m",
    "grid_dimension",
    "grid_tile_origin_x",
    "grid_tile_origin_y",
    "meters_to_grid_x",
    "meters_to_grid_y",
    "settlement_grid_rect",
    "settlement_meter_rect",
    "settlement_origin_m",
]
