from app.application.worldData.generators.coordinates.approachZ import (
    ApproachForm,
    approach_angle_deg,
    clamp_near_z_to_45,
    classify_approach,
)
from app.application.worldData.generators.coordinates.columnSurface import (
    column_surface,
    median_surface_z,
    resolve_district_pin_z,
)
from app.application.worldData.generators.coordinates.convert import (
    coarse_cell_fine_xy,
    coarse_tile_offset_fine,
    fine_to_grid_x,
    fine_to_grid_y,
    grid_dimension,
    grid_tile_origin_x,
    grid_tile_origin_y,
    map_cell_fine_span,
    settlement_origin_fine,
)
from app.application.worldData.generators.coordinates.rect import (
    cell_in_fine_rect,
    cell_in_surface_grid_rect,
    settlement_fine_rect,
    settlement_grid_rect,
)
from app.application.worldData.generators.coordinates.gridRay import walk_grid_ray
from app.application.worldData.generators.coordinates.worldTile import (
    expand_coarse_hydro_to_tile,
    fine_bbox_for_tile,
    iter_fine_chunks,
    iter_macro_tiles,
    is_macro_grid_coord,
    local_index_x,
    local_index_y,
    macro_bbox_to_fine_bbox,
    macro_tile_of,
    tile_index_x,
    tile_index_y,
    tile_origin_x,
    tile_origin_y,
    world_fine_xy,
)
from app.application.worldData.generators.coordinates.settlementCellRng import (
    SettlementCellRngRole,
    settlement_cell_rng,
)
from app.application.worldData.generators.coordinates.space import CoordinateSpace
from app.application.worldData.generators.coordinates.types import (
    FineDelta,
    FineGridCoord,
    FineGridRect,
    FineX,
    FineY,
    FineZ,
    GridX,
    GridY,
    SurfaceGridCoord,
    SurfaceGridRect,
)

__all__ = [
    "ApproachForm",
    "approach_angle_deg",
    "clamp_near_z_to_45",
    "classify_approach",
    "column_surface",
    "median_surface_z",
    "resolve_district_pin_z",
    "walk_grid_ray",
    "CoordinateSpace",
    "expand_coarse_hydro_to_tile",
    "iter_macro_tiles",
    "iter_fine_chunks",
    "is_macro_grid_coord",
    "local_index_x",
    "local_index_y",
    "macro_bbox_to_fine_bbox",
    "macro_tile_of",
    "fine_bbox_for_tile",
    "tile_index_x",
    "tile_index_y",
    "tile_origin_x",
    "tile_origin_y",
    "world_fine_xy",
    "GridX",
    "GridY",
    "FineGridCoord",
    "FineGridRect",
    "FineDelta",
    "FineX",
    "FineY",
    "FineZ",
    "SurfaceGridCoord",
    "SurfaceGridRect",
    "cell_in_fine_rect",
    "cell_in_surface_grid_rect",
    "map_cell_fine_span",
    "coarse_cell_fine_xy",
    "coarse_tile_offset_fine",
    "grid_dimension",
    "grid_tile_origin_x",
    "grid_tile_origin_y",
    "fine_to_grid_x",
    "fine_to_grid_y",
    "settlement_cell_rng",
    "SettlementCellRngRole",
    "settlement_grid_rect",
    "settlement_fine_rect",
    "settlement_origin_fine",
]
